#+TITLE: Linux course presentations

This repository contains a basic presentation series for my university.
The course aims to cover the basic, essential topics of Linux and to explain my own experiences with it.

Above all, this repository is a playground for me to test out LaTeX and Beamer features.

I welcome contributions of any sort!

Compilation requires BibLatex, Biber, [[https://pygments.org/][Pygments]], [[http://wiki.irmug.com/index.php?title=X_Series_2][XB Roya Font]] and [[https://github.com/be5invis/Iosevka][Iosevka]].

* Compilation

After meeting the requirements, you can run the =compile.sh= to get your outputs in the newly made =build/= folder:
  #+BEGIN_SRC
./compile.sh --publish
  #+END_SRC
or compile without the script and change the source code manually.

If you cannot meet the requirements or have problems of any sort with compilation process, please refer to [[https://github.com/MYDavoodeh/linux-course/releases][Releases]] and find a pre-compiled PDF suiting your needs.

** Different versions

*** Notes
The presenter notes. Comes with its own reference table (which often is often broken, use the Full References versions instead).

*** Original References
These versions are the "normal" slides. The references mentioned in notes are not included in the references tab.

*** Full References
Full References version includes all references (including the one mentioned in notes only).

*** Second Screen
The Second Screen version has both notes and a Full References version of the slides side by side in a single slide.

* Todo list

- Write a help message for =compiler.sh=
- *Important:* Fix the messed up header sections (LTR tree) of notes pdfs
- Make a light theme

* Keeping it consistent

- Paths and file names must use =mono= font.
- Everything other than the slides context must be in English. (Eventually, I will translate the slides.)
- All the generic files are Org files.
- Common properties and commands must be written in =src/header.tex=. (no other shared file with the current =compiler.sh=. If you aim to add more, modify the file as well.)
- In Preamble, the settings of each package should be directly below it.
- Logical sections of the codes should follow the syntax below (example used in =src/header.tex=):
  #+BEGIN_SRC
-----
BEGIN Section
-----

code

-----
END Section
-----
  #+END_SRC

-----
Yet figuring it out!
